### ISSUE TITLE
undefined method `authenticate' for Faraday::ConnectionOptions

### ISSUE THREAD

**Issue by elepedus** [octokit/octokit.rb#1103]
Just started using the Octokit gem, but when I try it out in the terminal I get a NoMethodError in Faraday: 
```
>> >> client = Octokit::Client.new(:access_token => 'token')
=> #<Octokit::Client:0x00007ffc918c1078 @adapter=:net_http, @faraday_config_block=nil, @api_version=3, @api_endpoint="https://api.github.com/", @web_endpoint="https://github.com/", @status_api_endpoint="https://status.github.com/api/", @login=nil, @password=nil, @proxy=nil, @oauth_token=nil, @client_id=nil, @client_secret=nil, @user_agent="Octokit Ruby Gem 1.25.0", @request_host=nil, @netrc=false, @auto_traversal=false, @per_page=nil>
>> >> user = client.user 'test'
Traceback (most recent call last):
       12: from (irb):10
       11: from /octokit_project/gems/octokit-1.25.0/lib/octokit/client/users.rb:41:in `user'
       10: from /octokit_project/gems/octokit-1.25.0/lib/octokit/request.rb:11:in `get'
        9: from /octokit_project/gems/octokit-1.25.0/lib/octokit/request.rb:65:in `request'
        8: from /octokit_project/gems/octokit-1.25.0/lib/octokit/connection.rb:25:in `connection'
        7: from /octokit_project/gems/faraday-0.15.4/lib/faraday.rb:70:in `new'
        6: from /octokit_project/gems/faraday-0.15.4/lib/faraday.rb:70:in `new'
        5: from /octokit_project/gems/faraday-0.15.4/lib/faraday/connection.rb:64:in `initialize'
        4: from /octokit_project/gems/faraday-0.15.4/lib/faraday/options.rb:60:in `merge'
        3: from /octokit_project/gems/faraday-0.15.4/lib/faraday/options.rb:49:in `merge!'
        2: from /octokit_project/gems/faraday-0.15.4/lib/faraday/options.rb:49:in `each'
        1: from /octokit_project/gems/faraday-0.15.4/lib/faraday/options.rb:50:in `block in merge!'
NoMethodError (undefined method `authenticate' for #<Faraday::ConnectionOptions:0x00007ffc918d1f18>)
>> 
```
What am I missing?

**Comment by elepedus** [comment]
No idea. I just did `bundle add octokit` and it defaulted to that version. Upgrading to latest fixed the issue – thank you!
