### ISSUE TITLE
`Octokit.contents` fails with URI-encoded filepath

### ISSUE THREAD

**Issue by ybiquitous** [octokit/octokit.rb#1128]
Hi, I find a bit strange behavior of the `Octokit.contents` method. When passing a URI-encoded file path, the method raises an error.

```ruby
test_file = "http%3A%2F%2Fexample.com/x y.rb"

puts URI.decode_www_form_component(test_file)
#=> http://example.com/x y.rb

Octokit.contents("ybiquitous/octokit-ruby-contents-reproduction", path: test_file)
#=> raise!
```

<details>
<summary>Error details</summary>

```
/private/tmp/workspace/octokit-ruby-contents-reproduction/vendor/bundle/gems/octokit-4.14.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/ybiquitous/octokit-ruby-contents-reproduction/contents/http:%2F%2Fexample.com/x%20y.rb: 404 - Not Found // See: https://developer.github.com/v3/repos/contents/#get-contents (Octokit::NotFound)
	from /private/tmp/workspace/octokit-ruby-contents-reproduction/vendor/bundle/gems/faraday-0.15.4/lib/faraday/response.rb:9:in `block in call'
	from /private/tmp/workspace/octokit-ruby-contents-reproduction/vendor/bundle/gems/faraday-0.15.4/lib/faraday/response.rb:61:in `on_complete'
	from /private/tmp/workspace/octokit-ruby-contents-reproduction/vendor/bundle/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
	from /private/tmp/workspace/octokit-ruby-contents-reproduction/vendor/bundle/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /private/tmp/workspace/octokit-ruby-contents-reproduction/vendor/bundle/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /private/tmp/workspace/octokit-ruby-contents-reproduction/vendor/bundle/gems/faraday-0.15.4/lib/faraday/request/retry.rb:128:in `call'
	from /private/tmp/workspace/octokit-ruby-contents-reproduction/vendor/bundle/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'
	from /private/tmp/workspace/octokit-ruby-contents-reproduction/vendor/bundle/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'
	from /private/tmp/workspace/octokit-ruby-contents-reproduction/vendor/bundle/gems/faraday-0.15.4/lib/faraday/connection.rb:138:in `get'
	from /private/tmp/workspace/octokit-ruby-contents-reproduction/vendor/bundle/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
	from /private/tmp/workspace/octokit-ruby-contents-reproduction/vendor/bundle/gems/octokit-4.14.0/lib/octokit/connection.rb:156:in `request'
	from /private/tmp/workspace/octokit-ruby-contents-reproduction/vendor/bundle/gems/octokit-4.14.0/lib/octokit/connection.rb:19:in `get'
	from /private/tmp/workspace/octokit-ruby-contents-reproduction/vendor/bundle/gems/octokit-4.14.0/lib/octokit/client/contents.rb:36:in `contents'
	from /private/tmp/workspace/octokit-ruby-contents-reproduction/vendor/bundle/gems/octokit-4.14.0/lib/octokit.rb:46:in `method_missing'
	from test.rb:7:in `<main>'
```

</details>

When encoding the file path before calling the method, the method works. For example:

```ruby
test_file = test_file
  .split("/")
  .map { |path_component| URI.encode_www_form_component(path_component).gsub("+", "%20") }
  .join("/")

puts test_file
#=> http%253A%252F%252Fexample.com/x%20y.rb

Octokit.contents("ybiquitous/octokit-ruby-contents-reproduction", path: test_file)
#=> good!
```

I think useful to encode a given file path inside the `contents` method, but I'm worrying the behavior change may be breaking. What do you think about this idea?

### Reproduction environment:
- Ruby 2.6.3
- Octokit 4.14.0
- macOS Movaje 10.14.5

### Reproduction code:
https://github.com/ybiquitous/octokit-ruby-contents-reproduction

**Comment by tarebyte** [comment]
@ybiquitous I believe that this maybe an issue with the API, not with the client.

Would you mind reaching out to GitHub Support to confirm?

Thanks!

**Comment by ybiquitous** [comment]
@tarebyte Thanks for the response. I sent a question to GitHub support! Let's wait for good news from support. 😏

**Comment by ybiquitous** [comment]
I received a response from GitHub support. In conclusion, there is no problem with the GitHub API.

1. <https://api.github.com/repos/ybiquitous/octokit-ruby-contents-reproduction/contents> returns:

```json5
[
  // ...
  {
    "name": "http%3A%2F%2Fexample.com",
    "path": "http%3A%2F%2Fexample.com",
    "sha": "6f4ef32fca9a60853b969115153dff9eb3afa7f6",
    "size": 0,
    "url": "https://api.github.com/repos/ybiquitous/octokit-ruby-contents-reproduction/contents/http%253A%252F%252Fexample.com?ref=master",
    "html_url": "https://github.com/ybiquitous/octokit-ruby-contents-reproduction/tree/master/http%253A%252F%252Fexample.com",
    "git_url": "https://api.github.com/repos/ybiquitous/octokit-ruby-contents-reproduction/git/trees/6f4ef32fca9a60853b969115153dff9eb3afa7f6",
    "download_url": null,
    "type": "dir",
    "_links": {
      "self": "https://api.github.com/repos/ybiquitous/octokit-ruby-contents-reproduction/contents/http%253A%252F%252Fexample.com?ref=master",
      "git": "https://api.github.com/repos/ybiquitous/octokit-ruby-contents-reproduction/git/trees/6f4ef32fca9a60853b969115153dff9eb3afa7f6",
      "html": "https://github.com/ybiquitous/octokit-ruby-contents-reproduction/tree/master/http%253A%252F%252Fexample.com"
    }
  },
  // ...
]
```

2. <https://api.github.com/repos/ybiquitous/octokit-ruby-contents-reproduction/contents/http%253A%252F%252Fexample.com?ref=master> (at `url`) returns:

```json
[
  {
    "name": "x y.rb",
    "path": "http%3A%2F%2Fexample.com/x y.rb",
    "sha": "e69de29bb2d1d6434b8b29ae775ad8c2e48c5391",
    "size": 0,
    "url": "https://api.github.com/repos/ybiquitous/octokit-ruby-contents-reproduction/contents/http%253A%252F%252Fexample.com/x%20y.rb?ref=master",
    "html_url": "https://github.com/ybiquitous/octokit-ruby-contents-reproduction/blob/master/http%253A%252F%252Fexample.com/x%20y.rb",
    "git_url": "https://api.github.com/repos/ybiquitous/octokit-ruby-contents-reproduction/git/blobs/e69de29bb2d1d6434b8b29ae775ad8c2e48c5391",
    "download_url": "https://raw.githubusercontent.com/ybiquitous/octokit-ruby-contents-reproduction/master/http%253A%252F%252Fexample.com/x%20y.rb",
    "type": "file",
    "_links": {
      "self": "https://api.github.com/repos/ybiquitous/octokit-ruby-contents-reproduction/contents/http%253A%252F%252Fexample.com/x%20y.rb?ref=master",
      "git": "https://api.github.com/repos/ybiquitous/octokit-ruby-contents-reproduction/git/blobs/e69de29bb2d1d6434b8b29ae775ad8c2e48c5391",
      "html": "https://github.com/ybiquitous/octokit-ruby-contents-reproduction/blob/master/http%253A%252F%252Fexample.com/x%20y.rb"
    }
  }
]
```

3. Get encoded URL: <https://api.github.com/repos/ybiquitous/octokit-ruby-contents-reproduction/contents/http%253A%252F%252Fexample.com/x%20y.rb?ref=master> (at `url`)

The support said:

> I don't see an error or problem here on our end. And yes, you should URL encode the file path before fetching it via the API.

So, API users should encode a file path.
