### ISSUE TITLE
Adding a team's repository permissions results in "422 - Validation Failed"

### ISSUE THREAD

**Issue by robkinyon-roivant** [octokit/octokit.rb#1283]
Using octokit 4.18.0, Ruby 2.4.7p357 on Amazon Linux 2

The error started on Sep 1st 2020. The code was working perfectly prior to that and has not been changed in months.

This is using `client.add_team_repository()` (https://octokit.github.io/octokit.rb/Octokit/Client/Organizations.html#add_team_repository-instance_method), invoked as so:
```ruby
client.add_team_repository( team_id, full_repo_slug, {
    permission: 'write',
})
```
The full debugging stack trace (with sensitive items omitted) is:
```
I, [2020-09-02T16:18:53.456246 #18009]  INFO -- request: PUT https://api.github.com/teams/<team_id>/repos/<org_name>/<repo_slug>
I, [2020-09-02T16:18:53.456305 #18009]  INFO -- request: Accept: "application/vnd.github.v3+json"
User-Agent: "Octokit Ruby Gem 4.18.0"
Content-Type: "application/json"
Authorization: "token <some token>"
I, [2020-09-02T16:18:53.565907 #18009]  INFO -- response: Status 422
I, [2020-09-02T16:18:53.566037 #18009]  INFO -- response: server: "GitHub.com"
date: "Wed, 02 Sep 2020 20:18:53 GMT"
content-type: "application/json; charset=utf-8"
content-length: "140"
status: "422 Unprocessable Entity"
x-oauth-scopes: "<some scopes which are enough>"
x-accepted-oauth-scopes: "admin:org, read:org, repo, user, write:org"
x-github-media-type: "github.v3; format=json"
deprecation: "Sat, 01 Feb 2020 00:00:00 GMT"
sunset: "Mon, 01 Feb 2021 00:00:00 GMT"
link: "<https://docs.github.com/changes/2020-01-21-moving-the-team-api-endpoints/>; rel=\"deprecation\"; type=\"text/html\", <https://api.github.com/organizations/<org_id>/team/<team_id>/repositories/<repo_id>>; rel=\"alternate\""
x-ratelimit-limit: "5000"
x-ratelimit-remaining: "4940"
x-ratelimit-reset: "1599080313"
access-control-expose-headers: "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset"
access-control-allow-origin: "*"
strict-transport-security: "max-age=31536000; includeSubdomains; preload"
x-frame-options: "deny"
x-content-type-options: "nosniff"
x-xss-protection: "1; mode=block"
referrer-policy: "origin-when-cross-origin, strict-origin-when-cross-origin"
content-security-policy: "default-src 'none'"
vary: "Accept-Encoding, Accept, X-Requested-With"
x-github-request-id: "<some request ID>"
<some script> aborted!
Octokit::UnprocessableEntity: PUT https://api.github.com/teams/<team_id>/repos/<org_name>/<repo_slug>: 422 - Validation Failed // See: https://docs.github.com/rest/reference/teams#add-or-update-team-repository-permissions
/usr/share/gems/gems/octokit-4.18.0/lib/octokit/response/raise_error.rb:16:in `on_complete'
/usr/share/gems/gems/faraday-1.0.1/lib/faraday/response.rb:12:in `block in call'
/usr/share/gems/gems/faraday-1.0.1/lib/faraday/response.rb:65:in `on_complete'
/usr/share/gems/gems/faraday-1.0.1/lib/faraday/response.rb:11:in `call'
/usr/share/gems/gems/octokit-4.18.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
/usr/share/gems/gems/octokit-4.18.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
/usr/share/gems/gems/faraday-1.0.1/lib/faraday/request/retry.rb:148:in `call'
/usr/share/gems/gems/faraday-1.0.1/lib/faraday/rack_builder.rb:153:in `build_response'
/usr/share/gems/gems/faraday-1.0.1/lib/faraday/connection.rb:492:in `run_request'
/usr/share/gems/gems/faraday-1.0.1/lib/faraday/connection.rb:279:in `put'
/usr/share/gems/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
/usr/share/gems/gems/octokit-4.18.0/lib/octokit/connection.rb:156:in `request'
/usr/share/gems/gems/octokit-4.18.0/lib/octokit/connection.rb:164:in `boolean_from_response'
/usr/share/gems/gems/octokit-4.18.0/lib/octokit/client/organizations.rb:541:in `add_team_repository'
<our code invoking client.add_team_repository() here>
```

**Comment by tarebyte** [comment]
@robkinyon-roivant according to the docs, `write` is not a valid permission.

<img width="730" alt="Screen Shot 2020-09-21 at 2 11 24 PM" src="https://user-images.githubusercontent.com/564113/93804467-568f5180-fc14-11ea-8b51-a2672d6d4f0a.png">

I think if you just update your `PUT` body to one of those permissions you should be good to go 👍
