### ISSUE TITLE
octokit.rb is incompatible with Faraday 1.1.0

### ISSUE THREAD

**Issue by csabahenk** [octokit/octokit.rb#1298]
I get this:

```
$ ruby -roctokit -e ''
[549975, #<Thread:0x000055a8b4d8ed68 run>, #<LoadError: cannot load such file -- octokit>, ["/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'", "/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'"]]
[549975, #<Thread:0x000055a8b4d8ed68 run>, #<RuntimeError: CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true>, ["/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:175:in `ensure in require'", "/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:175:in `require'", "/usr/lib/ruby/gems/2.7.0/gems/sawyer-0.8.2/lib/sawyer.rb:7:in `<top (required)>'", "/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'", "/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'", "/usr/lib/ruby/gems/2.7.0/gems/octokit-4.19.0/lib/octokit/connection.rb:1:in `<top (required)>'", "/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'", "/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'", "/usr/lib/ruby/gems/2.7.0/gems/octokit-4.19.0/lib/octokit/client.rb:1:in `<top (required)>'", "/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'", "/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'", "/usr/lib/ruby/gems/2.7.0/gems/octokit-4.19.0/lib/octokit.rb:1:in `<top (required)>'", "/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `require'", "/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'", "/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'"]]
[549975, #<Thread:0x000055a8b4d8ed68 run>, #<RuntimeError: CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true>, ["/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:175:in `ensure in require'", "/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:175:in `require'", "/usr/lib/ruby/gems/2.7.0/gems/octokit-4.19.0/lib/octokit/connection.rb:1:in `<top (required)>'", "/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'", "/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'", "/usr/lib/ruby/gems/2.7.0/gems/octokit-4.19.0/lib/octokit/client.rb:1:in `<top (required)>'", "/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'", "/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'", "/usr/lib/ruby/gems/2.7.0/gems/octokit-4.19.0/lib/octokit.rb:1:in `<top (required)>'", "/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `require'", "/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'", "/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'"]]
[549975, #<Thread:0x000055a8b4d8ed68 run>, #<RuntimeError: CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true>, ["/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:175:in `ensure in require'", "/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:175:in `require'", "/usr/lib/ruby/gems/2.7.0/gems/octokit-4.19.0/lib/octokit/client.rb:1:in `<top (required)>'", "/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'", "/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'", "/usr/lib/ruby/gems/2.7.0/gems/octokit-4.19.0/lib/octokit.rb:1:in `<top (required)>'", "/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `require'", "/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'", "/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'"]]
[549975, #<Thread:0x000055a8b4d8ed68 run>, #<RuntimeError: CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true>, ["/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:175:in `ensure in require'", "/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:175:in `require'", "/usr/lib/ruby/gems/2.7.0/gems/octokit-4.19.0/lib/octokit.rb:1:in `<top (required)>'", "/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `require'", "/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'", "/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'"]]
Traceback (most recent call last):
        1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- octokit (LoadError)
        14: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
        13: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
        12: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `require'
        11: from /usr/lib/ruby/gems/2.7.0/gems/octokit-4.19.0/lib/octokit.rb:1:in `<top (required)>'
        10: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
         9: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
         8: from /usr/lib/ruby/gems/2.7.0/gems/octokit-4.19.0/lib/octokit/client.rb:1:in `<top (required)>'
         7: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
         6: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
         5: from /usr/lib/ruby/gems/2.7.0/gems/octokit-4.19.0/lib/octokit/connection.rb:1:in `<top (required)>'
         4: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
         3: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
         2: from /usr/lib/ruby/gems/2.7.0/gems/sawyer-0.8.2/lib/sawyer.rb:7:in `<top (required)>'
         1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:175:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:175:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)
        11: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
        10: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
         9: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `require'
         8: from /usr/lib/ruby/gems/2.7.0/gems/octokit-4.19.0/lib/octokit.rb:1:in `<top (required)>'
         7: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
         6: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
         5: from /usr/lib/ruby/gems/2.7.0/gems/octokit-4.19.0/lib/octokit/client.rb:1:in `<top (required)>'
         4: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
         3: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
         2: from /usr/lib/ruby/gems/2.7.0/gems/octokit-4.19.0/lib/octokit/connection.rb:1:in `<top (required)>'
         1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:175:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:175:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)
        8: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
        7: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
        6: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `require'
        5: from /usr/lib/ruby/gems/2.7.0/gems/octokit-4.19.0/lib/octokit.rb:1:in `<top (required)>'
        4: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        3: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        2: from /usr/lib/ruby/gems/2.7.0/gems/octokit-4.19.0/lib/octokit/client.rb:1:in `<top (required)>'
        1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:175:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:175:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)
        5: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
        4: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
        3: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `require'
        2: from /usr/lib/ruby/gems/2.7.0/gems/octokit-4.19.0/lib/octokit.rb:1:in `<top (required)>'
        1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:175:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:175:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)
        1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:175:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:175:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)
```
on an up to date Arch Linux system, whereby:

```
$ pacman -Qi ruby ruby-octokit ruby-faraday
Name            : ruby
Version         : 2.7.2-1
Description     : An object-oriented language for quick and easy programming
Architecture    : x86_64
URL             : https://www.ruby-lang.org/en/
Licenses        : BSD  custom
Groups          : None
Provides        : None
Depends On      : gdbm  openssl  libffi  libyaml  gmp  zlib  rubygems  ruby-irb
Optional Deps   : ruby-docs: Ruby documentation [installed]
                  tk: for Ruby/TK
Required By     : ...
Optional For    : ...
Conflicts With  : None
Replaces        : None
Installed Size  : 13.35 MiB
Packager        : Anatol Pomozov <anatol.pomozov@gmail.com>
Build Date      : Fri 02 Oct 2020 04:56:52 PM CEST
Install Date    : Thu 08 Oct 2020 01:06:12 AM CEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

Name            : ruby-octokit
Version         : 4.19.0-1
Description     : Simple wrapper for the GitHub API.
Architecture    : any
URL             : https://github.com/octokit/octokit.rb
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : ruby-faraday  ruby-sawyer
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 433.39 KiB
Packager        : Unknown Packager
Build Date      : Thu 29 Oct 2020 04:27:30 PM CET
Install Date    : Thu 29 Oct 2020 04:27:35 PM CET
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None

Name            : ruby-faraday
Version         : 1.1.0-1
Description     : HTTP/REST API client library.
Architecture    : any
URL             : https://github.com/lostisland/faraday
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : ruby  ruby-multipart-post
Optional Deps   : None
Required By     : ruby-octokit  ruby-sawyer
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 559.99 KiB
Packager        : Felix Yan <felixonmars@archlinux.org>
Build Date      : Thu 22 Oct 2020 07:41:37 PM CEST
Install Date    : Thu 29 Oct 2020 04:26:26 PM CET
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```

whereas downgrading Faraday to 1.0.1 works around the problem.

**Comment by csabahenk** [comment]
The practical aspect of this issue is resolved downstream, see https://aur.archlinux.org/packages/ruby-octokit/#comment-802119.

However, that boils down to "octokit works with latest Faraday" (1.3.0, as of writing this). The gemspec still specifies

```ruby
 spec.add_dependency 'faraday', '>= 0.9'
 ```
 
and that still suspect for being incorrect, as this spec allows the problematic Faraday 1.1.0.

The problem might be a downstream Arch issue that is possible to amend the same way as the referred AUR comment suggests in context of Faraday 1.3.0. But until that is confirmed, or compatibility is confirmed some other way, Octokit compatibility with Faraday 1.1.0. is in doubt.

Also consider that said fix involves adding some implicit deps. Maybe those deps should be indicated explicitly (incuded in gemspec) by upstream.

 Hence I keep the issue open.

**Comment by nickfloyd** [comment]
Hey, thanks for the effort here. Given that this issue has been around for a while and many changes have been added since this was first introduced and we recently released some changes around [faraday usage](https://github.com/octokit/octokit.rb/releases/tag/v4.23.0), I am going to close this issue and mark it as stale. If you feel strongly about this needing to be implemented/asked please feel free to reopen and make the changes stated above and we’ll do what we can to get it merged in. Thanks again!
