### ISSUE TITLE
I learned 📖  that one file in RubyGems is modifying a string in-place: with Ruby 2.5, this became a problem.

### ISSUE THREAD

**Issue by Carloscota7676** [octokit/octokit.rb#1355]
I learned 📖  that one file in RubyGems is modifying a string in-place: with Ruby 2.5, this became a problem.

https://github.com/rubygems/rubygems/blob/master/lib/rubygems/bundler_version_finder.rb#L87

Output from test:

```
/opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/2.5.0/rubygems/bundler_version_finder.rb:89:in `untaint': can't modify frozen String (FrozenError)
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/2.5.0/rubygems/bundler_version_finder.rb:89:in `lockfile_contents'
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/2.5.0/rubygems/bundler_version_finder.rb:65:in `lockfile_version'
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/2.5.0/rubygems/bundler_version_finder.rb:19:in `bundler_version_with_reason'
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/2.5.0/rubygems/bundler_version_finder.rb:4:in `bundler_version'
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/2.5.0/rubygems/bundler_version_finder.rb:42:in `filter!'
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/2.5.0/rubygems/dependency.rb:283:in `matching_specs'
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/2.5.0/rubygems.rb:273:in `find_spec_for_exe'
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/2.5.0/rubygems.rb:303:in `activate_bin_path'
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/bin/bundle:23:in `<main>'
```

_Originally posted by @olleolleolle in https://github.com/octokit/octokit.rb/issues/1354#issuecomment-896576985_

**Comment by olleolleolle** [comment]
Oh, this can be closed, it's fixed in later releases of RubyGems - the linked Issue made that clear.

**Comment by AlreemH** [comment]
د
