### ISSUE TITLE
`Faraday::RackBuilder::StackLocked` occasionally when making requests

### ISSUE THREAD

**Issue by devonpmack** [octokit/octokit.rb#1406]
Occasionally we are seeing `Faraday::RackBuilder::StackLocked` when making requests through the GitHub client.

**Comment by radomirbosak** [comment]
This happens to me too. I get this kind of stack trace when calling `octokit.permission_level` occasionally. I'm not sure about the exact conditions when this happens.
```
vendor/bundle/ruby/3.0.0/gems/faraday-1.9.3/lib/faraday/rack_builder.rb:221:in `raise_if_locked': can't modify middleware stack after making a request (Faraday::RackBuilder::StackLocked)
    from vendor/bundle/ruby/3.0.0/gems/faraday-1.9.3/lib/faraday/rack_builder.rb:97:in `use'
    from vendor/bundle/ruby/3.0.0/gems/faraday-1.9.3/lib/faraday/rack_builder.rb:239:in `use_symbol'
    from vendor/bundle/ruby/3.0.0/gems/faraday-1.9.3/lib/faraday/rack_builder.rb:104:in `request'
    from /usr/local/lib/ruby/3.0.0/forwardable.rb:238:in `request'
    from vendor/bundle/ruby/3.0.0/gems/octokit-4.22.0/lib/octokit/connection.rb:112:in `block in agent'
    from vendor/bundle/ruby/3.0.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:48:in `initialize'
    from vendor/bundle/ruby/3.0.0/gems/octokit-4.22.0/lib/octokit/connection.rb:105:in `new'
    from vendor/bundle/ruby/3.0.0/gems/octokit-4.22.0/lib/octokit/connection.rb:105:in `agent'
    from vendor/bundle/ruby/3.0.0/gems/octokit-4.22.0/lib/octokit/connection.rb:156:in `request'
    from vendor/bundle/ruby/3.0.0/gems/octokit-4.22.0/lib/octokit/connection.rb:19:in `get'
    from vendor/bundle/ruby/3.0.0/gems/octokit-4.22.0/lib/octokit/client/repositories.rb:400:in `permission_level'
```

**Comment by pbstriker38** [comment]
We were having this issue and we solved it by adding explicit timeout options.

```ruby
Octokit::Client.new(
  access_token: access_token,
  connection_options: { request: { open_timeout: 5, timeout: 60 } }
)
```
