### ISSUE TITLE
SSL troubles on OS X

### ISSUE THREAD

**Issue by soffes** [octokit/octokit.rb#340]
I can run Bundler just fine with HTTPS sources, so I don't think my Ruby's SSL is broken. To be safe, I just uninstalled and reinstalled Ruby and OpenSSL. Bundler still works fine, but Octokit doesn't work.

I can do the same thing via cURL just fine with no errors as well.

```
$ ruby --version
ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin13.0.1]
$ irb
irb(main):001:0> require 'rubygems'
=> false
irb(main):002:0> require 'octokit'
=> true
irb(main):003:0> Octokit.repositories
Faraday::Error::ConnectionFailed: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
    from /Users/soffes/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/net/http.rb:918:in `connect'
    from /Users/soffes/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/net/http.rb:918:in `block in connect'
    from /Users/soffes/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
    from /Users/soffes/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/net/http.rb:918:in `connect'
    from /Users/soffes/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
    from /Users/soffes/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/net/http.rb:851:in `start'
    from /Users/soffes/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/net/http.rb:1367:in `request'
    from /Users/soffes/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/net/http.rb:1126:in `get'
    from /Users/soffes/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/faraday-0.8.7/lib/faraday/adapter/net_http.rb:73:in `perform_request'
    from /Users/soffes/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/faraday-0.8.7/lib/faraday/adapter/net_http.rb:38:in `call'
    from /Users/soffes/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/faraday-0.8.7/lib/faraday/response.rb:8:in `call'
    from /Users/soffes/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/faraday-0.8.7/lib/faraday/connection.rb:247:in `run_request'
    from /Users/soffes/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/faraday-0.8.7/lib/faraday/connection.rb:100:in `get'
    from /Users/soffes/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/sawyer-0.5.1/lib/sawyer/agent.rb:94:in `call'
    from /Users/soffes/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/octokit-2.6.0/lib/octokit/client.rb:247:in `request'
    from /Users/soffes/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/octokit-2.6.0/lib/octokit/client.rb:188:in `paginate'
    from /Users/soffes/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/octokit-2.6.0/lib/octokit/client/repositories.rb:63:in `repositories'
    from /Users/soffes/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/octokit-2.6.0/lib/octokit.rb:27:in `method_missing'
    from (irb):3
    from /Users/soffes/.rbenv/versions/2.0.0-p247/bin/irb:12:in `<main>'irb(main):004:0> 
```

**Comment by perlun** [comment]
This has re-appeared now. Running on Yosemite, and Homebrew has dropped the `curl-ca-bundle` package. :grin: 

Ruby 2.2.1. Any ideas?
