### ISSUE TITLE
Getting 403 on some "broken" repositories

### ISSUE THREAD

**Issue by Palleas** [octokit/octokit.rb#563]
Hi, 

I'm using the API (and octokit.rb) to find a bunch of repository and I'm getting a "403 forbidden" for this one: https://github.com/bs/starling (apparently there is an issue on disk).

````
/Users/romain/.rbenv/versions/2.2.0-preview2/lib/ruby/gems/2.2.0/gems/octokit-3.7.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/bs/starling: 403 - Repository access blocked (Octokit::Forbidden)
	from /Users/romain/.rbenv/versions/2.2.0-preview2/lib/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/response.rb:9:in `block in call'
	from /Users/romain/.rbenv/versions/2.2.0-preview2/lib/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
	from /Users/romain/.rbenv/versions/2.2.0-preview2/lib/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
	from /Users/romain/.rbenv/versions/2.2.0-preview2/lib/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/romain/.rbenv/versions/2.2.0-preview2/lib/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
	from /Users/romain/.rbenv/versions/2.2.0-preview2/lib/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:140:in `get'
	from /Users/romain/.rbenv/versions/2.2.0-preview2/lib/ruby/gems/2.2.0/gems/sawyer-0.6.0/lib/sawyer/agent.rb:94:in `call'
	from /Users/romain/.rbenv/versions/2.2.0-preview2/lib/ruby/gems/2.2.0/gems/octokit-3.7.0/lib/octokit/client.rb:339:in `request'
	from /Users/romain/.rbenv/versions/2.2.0-preview2/lib/ruby/gems/2.2.0/gems/octokit-3.7.0/lib/octokit/client.rb:135:in `get'
	from /Users/romain/.rbenv/versions/2.2.0-preview2/lib/ruby/gems/2.2.0/gems/octokit-3.7.0/lib/octokit/client/repositories.rb:26:in `repository'
	from ./search.rb:12:in `block (2 levels) in <main>'
	from ./search.rb:10:in `each'
	from ./search.rb:10:in `block in <main>'
	from ./search.rb:8:in `loop'
	from ./search.rb:8:in `<main>'
````

I'll handle the exception but I was wondering what was the point of making this repository available if 
I can't query it later on?

Regards,

Romain

**Comment by pengwynn** [comment]
@Palleas That `403` response is the way the API reports those as unavailable. It should be so rare that a `404` for a public repository would be more confusing. Are you coming across that repository from a list?

**Comment by Palleas** [comment]
Yes, I'm using the following code to find public repositories that I'm filtering later:

````ruby
require "octokit"

client = Octokit::Client.new :access_token => "..."
repos = client.all_repositories
repos.each do |repo|
    name = repo.full_name
    full_repo = client.repo(name) # 403
end
````

**Comment by pengwynn** [comment]
@Palleas We'll your odds of hitting them go up with that method. :grinning: 

I'd accept a patch if you want to add a new `RepositoryUnavailable` exception to [our growing list of `403`s][403].

[403]: https://github.com/octokit/octokit.rb/blob/master/lib/octokit/error.rb#L60-L70

**Comment by Palleas** [comment]
Haha I'm sorry but that's the only way I found to retrieve repositories with xcode projects because of the user / org / repo restriction.

PR on its way!
