### ISSUE TITLE
Using Octokit with Faraday causes issue The option: disable_ssl_peer_verification is invalid.

### ISSUE THREAD

**Issue by waynehoover** [octokit/octokit.rb#565]
Here is my configuration:
```
Octokit::Client.new(
   access_token: token_env,
   middleware: Faraday::RackBuilder.new{|b| b.adapter(:typhoeus)}
)
```

Here is the error:
```
The option: disable_ssl_peer_verification is invalid.
Please try ssl_verifypeer instead of disable_ssl_peer_verification.
```

Here is the relevant part of the stack trace:
```
/Users/w/.gem/ruby/2.2.0/gems/octokit-3.7.0/lib/octokit/client.rb:339:in `request'
/Users/w/.gem/ruby/2.2.0/gems/octokit-3.7.0/lib/octokit/client.rb:135:in `get'
/Users/w/.gem/ruby/2.2.0/gems/octokit-3.7.0/lib/octokit/client/users.rb:34:in `user'
/Users/w/.gem/ruby/2.2.0/gems/octokit-3.7.0/lib/octokit/configurable.rb:105:in `login'
/Users/w/.gem/ruby/2.2.0/gems/octokit-3.7.0/lib/octokit/client/events.rb:96:in `organization_events'
```

also when I try and do
```
    Octokit::Client.new(
      access_token: token_env,
      connection_options: {ssl_verifypeer: false},
      middleware: Faraday::RackBuilder.new{|b| b.adapter(:typhoeus)}
    )
```

I get the error:
```
undefined method `ssl_verifypeer=' for #<Faraday::ConnectionOptions:0x007fed1b121ca8>
```

So not sure if thats a different bug or related.

**Comment by rafalchmiel** [comment]
This is related to typhoeus/typhoeus#226. I tried out the solution and you just need to `require 'typhoeus/adapters/faraday'` to make the adapter work, as it says in that issue.

**Comment by waynehoover** [comment]
Thanks, that fixed it.
