### ISSUE TITLE
undefined method `[]=' for nil:NilClass (NoMethodError) on every request

### ISSUE THREAD

**Issue by fusillicode** [octokit/octokit.rb#607]
Hi, I'm instantiating an Octokit client with basic auth:
```
client = Octokit::Client.new \
  :login    => MyGem.configuration.login,
  :password => MyGem.configuration.password
```
and I'm getting the following error on every request (e.g. `client.user`):
```
/home/user/.rvm/gems/ruby-head/gems/faraday-0.9.1/lib/faraday/request.rb:67:in `[]=': undefined method `[]=' for nil:NilClass (NoMethodError)
	from <compiled>:1:in `params='
	from /home/user/.rvm/gems/ruby-head/gems/faraday-0.9.1/lib/faraday/request.rb:35:in `params='
	from /home/user/.rvm/gems/ruby-head/gems/faraday-0.9.1/lib/faraday/connection.rb:385:in `block in build_request'
	from /home/user/.rvm/gems/ruby-head/gems/faraday-0.9.1/lib/faraday/request.rb:26:in `block in create'
	from /home/user/.rvm/gems/ruby-head/gems/faraday-0.9.1/lib/faraday/request.rb:25:in `tap'
	from /home/user/.rvm/gems/ruby-head/gems/faraday-0.9.1/lib/faraday/request.rb:25:in `create'
	from /home/user/.rvm/gems/ruby-head/gems/faraday-0.9.1/lib/faraday/connection.rb:384:in `build_request'
	from /home/user/.rvm/gems/ruby-head/gems/faraday-0.9.1/lib/faraday/connection.rb:370:in `run_request'
	from /home/user/.rvm/gems/ruby-head/gems/faraday-0.9.1/lib/faraday/connection.rb:140:in `get'
	from /home/user/.rvm/gems/ruby-head/gems/sawyer-0.6.0/lib/sawyer/agent.rb:94:in `call'
	from /home/user/.rvm/gems/ruby-head/gems/octokit-3.8.0/lib/octokit/client.rb:339:in `request'
	from /home/user/.rvm/gems/ruby-head/gems/octokit-3.8.0/lib/octokit/client.rb:135:in `get'
	from /home/user/.rvm/gems/ruby-head/gems/octokit-3.8.0/lib/octokit/client/users.rb:34:in `user'
	from /home/user/path/to/mygem/lib/mygem/cli.rb:44:in `report'
	from /home/user/.rvm/gems/ruby-head/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/user/.rvm/gems/ruby-head/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/user/.rvm/gems/ruby-head/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/user/.rvm/gems/ruby-head/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from bin/mygem:5:in `<main>'
```
Is there something I'm missing or there is actually a problem with Octokit?

**Comment by pengwynn** [comment]
Hmm. Are you specifying any custom middleware? Are you getting the same error poking on Octokit in irb? I want to rule out anything in your application first.

**Comment by fusillicode** [comment]
No custom middleware as far as I know.
I've tried right now in irb and I get the same exact error :(

**Comment by pengwynn** [comment]
@fusillicode Have you tried string literals for your user/pass? Do you have 2FA enabled on that account?

**Comment by fusillicode** [comment]
Yes I tried string literals inside my app as well as in irb.

No 2FA for the account related to the login and pass supplied.

**Comment by fusillicode** [comment]
Ok I've solved by reinstalling the latest Ruby version (i.e. ruby-head) and updating all gems (i.e. `gem update`).

I think that the problem was related to openssl but sincerely I can't confirm that.

I close the issue for now.
