### ISSUE TITLE
Cannot close_pull_request

### ISSUE THREAD

**Issue by caarlos0** [octokit/octokit.rb#613]
Got this error trying to close a PR using Octokit:

```
/home/carlos/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/octokit-3.8.0/lib/octokit/response/raise_error.rb:16:in `on_complete': PATCH https://api.github.com/repos/ContaAzul/intern-challenge/pulls/16: 404 - Not Found // See: https://developer.github.com/v3 (Octokit::NotFound)
```

This PR is in a private repo, so I generated an app token with access to it to use with Octokit.

My code looks like:

```ruby
client = Octokit::Client.new access_token: TOKEN
client.repositories("ContaAzul").each do |repo|
  client.pulls(repo.full_name, state: :open).each do |pull|
     client.close_pull_request repo.full_name, pull.number if ~some rules apply~
  end
end
```

According to docs this should work, but I got that error instead...

**Comment by caarlos0** [comment]
BTW, same happens with octokit 3.7.1:

```
/usr/local/rvm/gems/ruby-2.2.0/gems/octokit-3.7.1/lib/octokit/response/raise_error.rb:16:in `on_complete': PATCH https://api.github.com/repos/ContaAzul/intern-challenge/pulls/16: 404 - Not Found // See: https://developer.github.com/v3 (Octokit::NotFound)
	from /usr/local/rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/response.rb:9:in `block in call'
	from /usr/local/rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
	from /usr/local/rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
	from /usr/local/rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /usr/local/rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
	from /usr/local/rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:177:in `patch'
	from /usr/local/rvm/gems/ruby-2.2.0/gems/sawyer-0.6.0/lib/sawyer/agent.rb:94:in `call'
	from /usr/local/rvm/gems/ruby-2.2.0/gems/octokit-3.7.1/lib/octokit/client.rb:339:in `request'
	from /usr/local/rvm/gems/ruby-2.2.0/gems/octokit-3.7.1/lib/octokit/client.rb:162:in `patch'
	from /usr/local/rvm/gems/ruby-2.2.0/gems/octokit-3.7.1/lib/octokit/client/pull_requests.rb:118:in `update_pull_request'
	from /usr/local/rvm/gems/ruby-2.2.0/gems/octokit-3.7.1/lib/octokit/client/pull_requests.rb:131:in `close_pull_request'
	from ./build/angry_bot.rb:42:in `check'
	from ./build/angry_bot.rb:65:in `block (2 levels) in check_all'
	from ./build/angry_bot.rb:65:in `each'
	from ./build/angry_bot.rb:65:in `block in check_all'
	from ./build/angry_bot.rb:64:in `each'
	from ./build/angry_bot.rb:64:in `check_all'
	from ./build/angry_bot.rb:58:in `block in work'
	from ./build/angry_bot.rb:57:in `each'
	from ./build/angry_bot.rb:57:in `work'
	from ./build/angry_bot.rb:71:in `<main>'
```

**Comment by pengwynn** [comment]
It appears from the logs you're authenticating as a user who doesn't have push access to the repository. Without push access, you can only close your own pull requests. Does that help?

Ideally, that would be a `403`, but we've got a few places in the API that return `404` for insufficient permissions due to the way we avoid info leaks in private repos.
