### ISSUE TITLE
Create pull request by Octokit sometimes failed 

### ISSUE THREAD

**Issue by JuanitoFatas** [octokit/octokit.rb#622]
I have a method to send pull request by Octokit:

```ruby
def send_pull_request(repo_info, commit_message, title, body)
  create_branch(repo_info[:full_github_name], with_head, repo_info[:master_sha])

  update_contents(
    repo_info[:full_github_name],
    "Gemfile.lock",
    commit_message,
    repo_info[:file_sha],
    repo_info[:file_content],
    branch: branch_name
  )

  create_pull_request(
    repo_info[:full_github_name],
    "master",
    branch_name,
    title,
    body
  )
end
```

`repo_info` looks like this (fake data):

```ruby
{
  full_github_name: "foo/bar",
  master_sha: "7638417db6d59f3c431d3e1f261cc637155684cd",
  file_sha: "95b966ae1c166bd92f8ae7d1c313e738c731dfc3",
  file_content: "changed",
}
```

It works really well but intermittently I saw errors like:

- POST 404 with refs API

  ```
  POST https://api.github.com/repos/foo/bar/git/refs: 404 -
  Not Found // See: https://developer.github.com/v3/git/refs/#create-a-reference
  lib/octokit/github_client/dsl.rb:4:in `create_branch'
  ```

- No commits between master and newly-created-branch

  ```
  POST https://api.github.com/repos/foo/bar/pulls: 422 - Validation Failed
  Error summary:
    resource: PullRequest
    code: custom
    message: No commits between master and newly-created-branch
  // See: https://developer.github.com/v3/pulls/#create-a-pull-request
  lib/octokit/github_client.rb:14:in `create_pull_request'
  ```

Anything wrong with my setup? Any way can my `send_pull_request` method to be improved?

Thanks in advance!

**Comment by joeyw** [comment]
@JuanitoFatas Hi Juanito, are you still having this problem?

For the Refs api with 404, that is likely indicating an issue with the repository name parameter. Either the name is wrong or the token being used is missing the correct scope. The create_ref api will return other validation errors for a bad ref name or bad sha.

**Comment by JuanitoFatas** [comment]
Not seeing this error recently. Thanks for the explanations, Joey!
