### ISSUE TITLE
Encoding::UndefinedConversionError

### ISSUE THREAD

**Issue by Nekromancer** [octokit/octokit.rb#637]
I just got an conversin exception on a code that was working just fine yesterday. Code:

```ruby
@repositories = Octokit.repositories current_user.uid.to_i
```
Exception on this lane:
```
Encoding::UndefinedConversionError - "\xC5" from ASCII-8BIT to UTF-8:
  json (1.8.3) lib/json/common.rb:223:in `generate'
  json (1.8.3) lib/json/common.rb:394:in `dump'
  faraday-http-cache (1.2.0) lib/faraday/http_cache/storage.rb:132:in `serialize_object'
  faraday-http-cache (1.2.0) lib/faraday/http_cache/storage.rb:128:in `block in serialize_entry'
  faraday-http-cache (1.2.0) lib/faraday/http_cache/storage.rb:128:in `serialize_entry'
  faraday-http-cache (1.2.0) lib/faraday/http_cache/storage.rb:46:in `write'
  faraday-http-cache (1.2.0) lib/faraday/http_cache.rb:271:in `store'
  faraday-http-cache (1.2.0) lib/faraday/http_cache.rb:297:in `block in fetch'
  faraday (0.9.1) lib/faraday/response.rb:57:in `on_complete'
  faraday-http-cache (1.2.0) lib/faraday/http_cache.rb:295:in `fetch'
  faraday-http-cache (1.2.0) lib/faraday/http_cache.rb:202:in `process'
  faraday-http-cache (1.2.0) lib/faraday/http_cache.rb:140:in `call!'
  faraday-http-cache (1.2.0) lib/faraday/http_cache.rb:113:in `call'
  faraday (0.9.1) lib/faraday/rack_builder.rb:139:in `build_response'
  faraday (0.9.1) lib/faraday/connection.rb:377:in `run_request'
  faraday (0.9.1) lib/faraday/connection.rb:140:in `get'
  sawyer (0.6.0) lib/sawyer/agent.rb:94:in `call'
  octokit (4.0.1) lib/octokit/connection.rb:154:in `request'
  octokit (4.0.1) lib/octokit/connection.rb:84:in `paginate'
  octokit (4.0.1) lib/octokit/client/repositories.rb:68:in `repositories'
  octokit (4.0.1) lib/octokit.rb:46:in `method_missing'
  app/controllers/projects_controller.rb:23:in `new'
```

**Comment by Nekromancer** [comment]
Ok, it was a problem with faraday-http-cache. I needed to change serializer to Marshal. Unfortunetely its hack and not really a solution. Link: https://github.com/plataformatec/faraday-http-cache/issues/38
