### ISSUE TITLE
Unable to fetch patch from private repo.

### ISSUE THREAD

**Issue by md5** [octokit/octokit.rb#657]
I've got some code that looks like this:

```ruby
client = Octokit.client(auth_token: ENV['TOKEN'])
puts client.pulls('myorg/repo').map do |pull|
  pull.rels[:patch].get.data
end
```

When I do this for a private repository, I get this error:

```console
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/octokit-4.1.1/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://github.com/myorg/myrepo/pull/1.patch: 404 - Not Found (Octokit::NotFound)
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/octokit-4.1.1/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/octokit-4.1.1/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sawyer-0.6.0/lib/sawyer/agent.rb:94:in `call'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sawyer-0.6.0/lib/sawyer/relation.rb:264:in `call'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sawyer-0.6.0/lib/sawyer/relation.rb:163:in `get'
	from ./github-issue-mover:99:in `block in <main>'
	from ./github-issue-mover:98:in `each'
	from ./github-issue-mover:98:in `<main>'
```

It looks like I get the same result when using Curl too:

```console
$ curl -H 'Authorization: token 000000000000000000000000' https://github.com/myorg/repo/pull/113.patch
{"error":"Not Found"}
```

Any ideas?

**Comment by md5** [comment]
I just figured it out. The issue is this (from [the docs](https://developer.github.com/v3/pulls/#response-1)):

> Pass the appropriate [media type](https://developer.github.com/v3/media/#commits-commit-comparison-and-pull-requests) to fetch diff and patch formats.

I changed my code to do something like this instead:

```ruby
client = Octokit.client(auth_token: ENV['TOKEN'])
puts client.pulls('myorg/repo').map do |pull|
  client.pull('myorg/repo', pull.number, accept: 'application/vnd.github.v3.patch')
end
```

That was super confusing...
