### ISSUE TITLE
Getting a 404 when creating a PR

### ISSUE THREAD

**Issue by emirkin** [octokit/octokit.rb#731]
I get an error when using `create_pull_request` method to create a PR from my branch in my fork to master on the primary (see the values I use below)
```
D, [2016-03-12T19:21:36.651824 #21487] DEBUG -- : Creating PR: {:title=>"...", :description=>"...", :base=>"myorg/master", :head=>"emirkin/mybranch", :repo=>"myorg/myrepo"}

/Users/bigbubba/.rvm/gems/ruby-2.2.3/gems/octokit-4.3.0/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/myorg/myrepo/pulls: 404 - Not Found // See: https://developer.github.com/v3/pulls/#create-a-pull-request (Octokit::NotFound)
	from /Users/bigbubba/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
	from /Users/bigbubba/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
	from /Users/bigbubba/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
	from /Users/bigbubba/.rvm/gems/ruby-2.2.3/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /Users/bigbubba/.rvm/gems/ruby-2.2.3/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /Users/bigbubba/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/bigbubba/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Users/bigbubba/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /Users/bigbubba/.rvm/gems/ruby-2.2.3/gems/sawyer-0.7.0/lib/sawyer/agent.rb:94:in `call'
	from /Users/bigbubba/.rvm/gems/ruby-2.2.3/gems/octokit-4.3.0/lib/octokit/connection.rb:154:in `request'
	from /Users/bigbubba/.rvm/gems/ruby-2.2.3/gems/octokit-4.3.0/lib/octokit/connection.rb:28:in `post'
	from /Users/bigbubba/.rvm/gems/ruby-2.2.3/gems/octokit-4.3.0/lib/octokit/client/pull_requests.rb:57:in `create_pull_request'
	from /Users/bigbubba/.rvm/gems/ruby-2.2.3/gems/octokit-4.3.0/lib/octokit.rb:46:in `method_missing'
```

Am I using this method incorrectly?

**Comment by emirkin** [comment]
Silly me. Same issue as in https://github.com/octokit/octokit.rb/issues/510.
