### ISSUE TITLE
Calling the `hooks` method on the Octokit client does not pass along authentication

### ISSUE THREAD

**Issue by bsnchan** [octokit/octokit.rb#735]
Using the Octokit v4.3.0, attempting to fetch the repo hooks for my repo is returning 404:

```
irb(main):001:0> require 'octokit'
=> true
irb(main):002:0> github_client = Octokit::Client.new(login: 'myuser', oauth_token: 'myauthtoken')
=> #<Octokit::Client:0x007f8e6f04e8e0 @access_token=nil, @api_endpoint="https://api.github.com", @auto_paginate=nil, @client_id=nil, @client_secret=nil, @connection_options={:headers=>{:accept=>"application/vnd.github.v3+json", :user_agent=>"Octokit Ruby Gem 4.3.0"}}, @default_media_type="application/vnd.github.v3+json", @login="myuser", @management_console_endpoint=nil, @management_console_password=nil, @middleware=#<Faraday::RackBuilder:0x007f8e6bb04608 @handlers=[Octokit::Middleware::FollowRedirects, Octokit::Response::RaiseError, Octokit::Response::FeedParser, Faraday::Adapter::NetHttp]>, @netrc=false, @netrc_file="/Users/pivotal/.netrc", @per_page=nil, @password=nil, @proxy=nil, @user_agent="Octokit Ruby Gem 4.3.0", @web_endpoint="https://github.com">

irb(main):003:0> github_client.hooks('cloudfoundry-incubator/.NET-sample-app')
Octokit::NotFound: GET https://api.github.com/repositories/44834674/hooks: 404 - Not Found // See: https://developer.github.com/v3
  from /Users/pivotal/.gem/ruby/2.3.0/gems/octokit-4.3.0/lib/octokit/response/raise_error.rb:16:in `on_complete'
  from /Users/pivotal/.gem/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
  from /Users/pivotal/.gem/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
  from /Users/pivotal/.gem/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
  from /Users/pivotal/.gem/ruby/2.3.0/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
  from /Users/pivotal/.gem/ruby/2.3.0/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:79:in `block in perform_with_redirection'
  from /Users/pivotal/.gem/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
  from /Users/pivotal/.gem/ruby/2.3.0/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:75:in `perform_with_redirection'
  from /Users/pivotal/.gem/ruby/2.3.0/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
  from /Users/pivotal/.gem/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
  from /Users/pivotal/.gem/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
  from /Users/pivotal/.gem/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
  from /Users/pivotal/.gem/ruby/2.3.0/gems/sawyer-0.7.0/lib/sawyer/agent.rb:94:in `call'
  from /Users/pivotal/.gem/ruby/2.3.0/gems/octokit-4.3.0/lib/octokit/connection.rb:154:in `request'
  from /Users/pivotal/.gem/ruby/2.3.0/gems/octokit-4.3.0/lib/octokit/connection.rb:84:in `paginate'
  from /Users/pivotal/.gem/ruby/2.3.0/gems/octokit-4.3.0/lib/octokit/client/hooks.rb:27:in `hooks'
  from (irb):3
  from /Users/pivotal/.rubies/2.3.0/bin/irb:11:in `<main>'irb(main):004:0>
```

Looking at the error, it appears that the Octokit client is getting a 404 from the Github API. I then tried to get the hooks for my repo using `curl` and was successfully able to do so:

```
± gd+bc |master ✓| → curl -I -H 'Authorization: token mytoken' https://api.github.com/repositories/44834674/hooks
HTTP/1.1 200 OK
Server: GitHub.com
Date: Fri, 18 Mar 2016 19:50:43 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 3053
Status: 200 OK
```

It seems like the 404 message is returned if you attempt to perform the GET requests without authentication:

```
± gd+bc |master ✓| → curl -I https://api.github.com/repositories/44834674/hooks
HTTP/1.1 404 Not Found
Server: GitHub.com
Date: Fri, 18 Mar 2016 19:52:03 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 87
Status: 404 Not Found
```

Note that this previously worked using Octokit v2.7.1:
```
± gd+bc |master U:1 ✗| → irb
reqirb(main):001:0> require 'octokit'
=> true
irb(main):002:0> github_client = Octokit::Client.new(login: 'myuser', oauth_token: 'myauthtoken')
=> #<Octokit::Client:0x007f812cbc3e50 @access_token=nil, @api_endpoint="https://api.github.com", @auto_paginate=nil, @client_id=nil, @client_secret=nil, @connection_options={:headers=>{:accept=>"application/vnd.github.beta+json", :user_agent=>"Octokit Ruby Gem 2.7.1"}}, @default_media_type="application/vnd.github.beta+json", @login="cfdreddbot", @middleware=#<Faraday::RackBuilder:0x007f812ce42eb0 @handlers=[Octokit::Response::RaiseError, Octokit::Response::FeedParser, Faraday::Adapter::NetHttp]>, @netrc=false, @netrc_file="/Users/pivotal/.netrc", @per_page=nil, @password=nil, @proxy=nil, @user_agent="Octokit Ruby Gem 2.7.1", @web_endpoint="https://github.com">
irb(main):003:0> github_client.hooks('cloudfoundry-incubator/.NET-sample-app')
=> #<Sawyer::Resource:0x007f812d16cd70 @_agent=<Sawyer::Agent https://api.github.com/>, @_rels=#<Sawyer::Relation::Map: [:self, :documentation]>, @_fields=#<Set: {:message}>, @_metaclass=#<Class:#<Sawyer::Resource:0x007f812d16cd70>>, @attrs={:message=>"Moved Permanently"}>
```

**Comment by tarebyte** [comment]
@bsnchan it looks like you used `oauth_token` instead of `access_token`

Does this work?
```ruby
github_client = Octokit::Client.new(access_token: 'myauthtoken')
```

**Comment by bsnchan** [comment]
@tarebyte Worked like a charm :) Clearly I'm not reading documentation. Thanks!
