### ISSUE TITLE
Caching, as decribed in readme is not working and crashing on UTF-8

### ISSUE THREAD

**Issue by matkoniecz** [octokit/octokit.rb#764]
```
require 'octokit'
require 'faraday-http-cache'

stack = Faraday::RackBuilder.new do |builder|
  builder.use Faraday::HttpCache
  builder.use Octokit::Response::RaiseError
  builder.adapter Faraday.default_adapter
end
Octokit.middleware = stack

Octokit.user 'matkoniecz'
```

results in

```
/var/lib/gems/2.2.0/gems/json-1.8.3/lib/json/common.rb:223:in `encode': "\xC3" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
	from /var/lib/gems/2.2.0/gems/json-1.8.3/lib/json/common.rb:223:in `generate'
	from /var/lib/gems/2.2.0/gems/json-1.8.3/lib/json/common.rb:223:in `generate'
	from /var/lib/gems/2.2.0/gems/json-1.8.3/lib/json/common.rb:394:in `dump'
	from /home/mateusz/.gem/ruby/2.2.0/gems/faraday-http-cache-1.3.0/lib/faraday/http_cache/storage.rb:132:in `serialize_object'
	from /home/mateusz/.gem/ruby/2.2.0/gems/faraday-http-cache-1.3.0/lib/faraday/http_cache/storage.rb:128:in `block in serialize_entry'
	from /home/mateusz/.gem/ruby/2.2.0/gems/faraday-http-cache-1.3.0/lib/faraday/http_cache/storage.rb:128:in `map'
	from /home/mateusz/.gem/ruby/2.2.0/gems/faraday-http-cache-1.3.0/lib/faraday/http_cache/storage.rb:128:in `serialize_entry'
	from /home/mateusz/.gem/ruby/2.2.0/gems/faraday-http-cache-1.3.0/lib/faraday/http_cache/storage.rb:46:in `write'
	from /home/mateusz/.gem/ruby/2.2.0/gems/faraday-http-cache-1.3.0/lib/faraday/http_cache.rb:279:in `store'
	from /home/mateusz/.gem/ruby/2.2.0/gems/faraday-http-cache-1.3.0/lib/faraday/http_cache.rb:305:in `block in fetch'
	from /home/mateusz/.gem/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
	from /home/mateusz/.gem/ruby/2.2.0/gems/faraday-http-cache-1.3.0/lib/faraday/http_cache.rb:303:in `fetch'
	from /home/mateusz/.gem/ruby/2.2.0/gems/faraday-http-cache-1.3.0/lib/faraday/http_cache.rb:208:in `process'
	from /home/mateusz/.gem/ruby/2.2.0/gems/faraday-http-cache-1.3.0/lib/faraday/http_cache.rb:146:in `call!'
	from /home/mateusz/.gem/ruby/2.2.0/gems/faraday-http-cache-1.3.0/lib/faraday/http_cache.rb:119:in `call'
	from /home/mateusz/.gem/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /home/mateusz/.gem/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /home/mateusz/.gem/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
	from /home/mateusz/.gem/ruby/2.2.0/gems/sawyer-0.7.0/lib/sawyer/agent.rb:94:in `call'
	from /home/mateusz/.gem/ruby/2.2.0/gems/octokit-4.3.0/lib/octokit/connection.rb:154:in `request'
	from /home/mateusz/.gem/ruby/2.2.0/gems/octokit-4.3.0/lib/octokit/connection.rb:19:in `get'
	from /home/mateusz/.gem/ruby/2.2.0/gems/octokit-4.3.0/lib/octokit/client/users.rb:34:in `user'
	from /home/mateusz/.gem/ruby/2.2.0/gems/octokit-4.3.0/lib/octokit.rb:46:in `method_missing'
```

Note that

```
Octokit.user 'jbarnette'
```

works, so it seems that YA programmer assumed that only ASCII exists.

**Comment by matkoniecz** [comment]
And obviously, removing 

```
stack = Faraday::RackBuilder.new do |builder|
  builder.use Faraday::HttpCache
  builder.use Octokit::Response::RaiseError
  builder.adapter Faraday.default_adapter
end
Octokit.middleware = stack
```

causes error to go away.

**Comment by matkoniecz** [comment]
Together with #732 and similar I am starting to consider using octokit as a mistake. Maybe it would be easier to use bare REST API.

**Comment by pengwynn** [comment]
Looks like the actual bug is over in https://github.com/plataformatec/faraday-http-cache/issues/38. You might try:

```ruby
stack = Faraday::RackBuilder.new do |builder|
   builder.use Faraday::HttpCache, :serializer => Marshal
  builder.use Octokit::Response::RaiseError
  builder.adapter Faraday.default_adapter
end
Octokit.middleware = stack
```

> Together with #732 and similar I am starting to consider using octokit as a mistake. Maybe it would be easier to use bare REST API.

Always an option.
