### ISSUE TITLE
uninitialized constant Faraday::HttpCache

### ISSUE THREAD

**Issue by Nakilon** [octokit/octokit.rb#795]
On doing this from README:

```ruby
require "octokit"
stack = Faraday::RackBuilder.new do |builder|
  builder.use Faraday::HttpCache, serializer: Marshal, shared_cache: false
  builder.use Octokit::Response::RaiseError
  builder.adapter Faraday.default_adapter
end
Octokit.middleware = stack
```

I get this:

```
/Users/nakilon/.gem/gems/faraday-0.9.2/lib/faraday.rb:236:in `const_missing': uninitialized constant Faraday::HttpCache (NameError)
	from main.rb:57:in `block in <main>'
	from /Users/nakilon/.gem/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:66:in `build'
	from /Users/nakilon/.gem/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:55:in `initialize'
```

Mac OS El Captain.

```
$ bundle exec gem list

*** LOCAL GEMS ***

addressable (2.4.0)
bundler (1.12.5)
faraday (0.9.2)
faraday-http-cache (1.3.1)
multipart-post (2.0.0)
octokit (4.3.0)
sawyer (0.7.0)
```

**Comment by tarebyte** [comment]
@Nakilon you'll need to require `faraday-http-cache' in your file as well.

```ruby
require "octokit"
require "faraday-http-cache"

stack = Faraday::RackBuilder.new do |builder|
  builder.use Faraday::HttpCache, serializer: Marshal, shared_cache: false
  builder.use Octokit::Response::RaiseError
  builder.adapter Faraday.default_adapter
end
Octokit.middleware = stack
```

should work
